/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
/**
 *
 * @author PRITHVI MUKESH
 */
public class game11 extends javax.swing.JFrame {

           int a1=0,a2=0,a3=0,a4=0,a5=0,a6=0;
          int n=0,q=1,r=0;
          String n1,n2,n3,n4,ms;
          int r11=0,r12=0,r13=0,r14=0,r15=0,r16=0;
          int r21=0,r22=0,r23=0,r24=0,r25=0,r26=0;
          int r31=0,r32=0,r33=0,r34=0,r35=0,r36=0;
          int r41=0,r42=0,r43=0,r44=0,r45=0,r46=0;
          int r51=0,r52=0,r53=0,r54=0,r55=0,r56=0;
          int r61=0,r62=0,r63=0,r64=0,r65=0,r66=0;
    public game11(String s,int n,String n1,String n2,String n3,String n4) {
        initComponents();
          l.setText(s);
       
        l1.setText(n3);
        l2.setText(n4);
        
        this.n=n;
        this.n1=n1;
        this.n2=n2;
    }

    private game11() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        b12 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        b46 = new javax.swing.JButton();
        b45 = new javax.swing.JButton();
        b52 = new javax.swing.JButton();
        b51 = new javax.swing.JButton();
        b54 = new javax.swing.JButton();
        b53 = new javax.swing.JButton();
        b56 = new javax.swing.JButton();
        b55 = new javax.swing.JButton();
        b62 = new javax.swing.JButton();
        b61 = new javax.swing.JButton();
        b64 = new javax.swing.JButton();
        b63 = new javax.swing.JButton();
        b66 = new javax.swing.JButton();
        b65 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        getContentPane().add(l);
        l.setBounds(280, 20, 500, 40);

        l1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(l1);
        l1.setBounds(380, 100, 330, 40);

        l2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(l2);
        l2.setBounds(390, 140, 330, 40);
        getContentPane().add(b12);
        b12.setBounds(330, 220, 70, 50);
        getContentPane().add(b11);
        b11.setBounds(260, 220, 70, 50);
        getContentPane().add(b14);
        b14.setBounds(470, 220, 70, 50);
        getContentPane().add(b13);
        b13.setBounds(400, 220, 70, 50);

        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        getContentPane().add(b16);
        b16.setBounds(610, 220, 70, 50);
        getContentPane().add(b15);
        b15.setBounds(540, 220, 70, 50);
        getContentPane().add(b22);
        b22.setBounds(330, 270, 70, 50);
        getContentPane().add(b21);
        b21.setBounds(260, 270, 70, 50);
        getContentPane().add(b24);
        b24.setBounds(470, 270, 70, 50);
        getContentPane().add(b23);
        b23.setBounds(400, 270, 70, 50);
        getContentPane().add(b26);
        b26.setBounds(610, 270, 70, 50);
        getContentPane().add(b25);
        b25.setBounds(540, 270, 70, 50);
        getContentPane().add(b32);
        b32.setBounds(330, 320, 70, 50);
        getContentPane().add(b31);
        b31.setBounds(260, 320, 70, 50);
        getContentPane().add(b34);
        b34.setBounds(470, 320, 70, 50);
        getContentPane().add(b33);
        b33.setBounds(400, 320, 70, 50);
        getContentPane().add(b36);
        b36.setBounds(610, 320, 70, 50);
        getContentPane().add(b35);
        b35.setBounds(540, 320, 70, 50);
        getContentPane().add(b42);
        b42.setBounds(330, 370, 70, 50);
        getContentPane().add(b41);
        b41.setBounds(260, 370, 70, 50);
        getContentPane().add(b44);
        b44.setBounds(470, 370, 70, 50);
        getContentPane().add(b43);
        b43.setBounds(400, 370, 70, 50);
        getContentPane().add(b46);
        b46.setBounds(610, 370, 70, 50);
        getContentPane().add(b45);
        b45.setBounds(540, 370, 70, 50);
        getContentPane().add(b52);
        b52.setBounds(330, 420, 70, 50);
        getContentPane().add(b51);
        b51.setBounds(260, 420, 70, 50);
        getContentPane().add(b54);
        b54.setBounds(470, 420, 70, 50);
        getContentPane().add(b53);
        b53.setBounds(400, 420, 70, 50);
        getContentPane().add(b56);
        b56.setBounds(610, 420, 70, 50);
        getContentPane().add(b55);
        b55.setBounds(540, 420, 70, 50);
        getContentPane().add(b62);
        b62.setBounds(330, 470, 70, 50);
        getContentPane().add(b61);
        b61.setBounds(260, 470, 70, 50);
        getContentPane().add(b64);
        b64.setBounds(470, 470, 70, 50);
        getContentPane().add(b63);
        b63.setBounds(400, 470, 70, 50);
        getContentPane().add(b66);
        b66.setBounds(610, 470, 70, 50);
        getContentPane().add(b65);
        b65.setBounds(540, 470, 70, 50);

        c1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        c1.setText("1");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(260, 550, 70, 50);

        c2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        c2.setText("2");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(330, 550, 70, 50);

        c4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        c4.setText("4");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4);
        c4.setBounds(470, 550, 70, 50);

        c3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        c3.setText("3");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(400, 550, 70, 50);

        c6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        c6.setText("6");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6);
        c6.setBounds(610, 550, 70, 50);

        c5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        c5.setText("5");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5);
        c5.setBounds(540, 550, 70, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark_aurora-2560x1600.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 670);

        setBounds(0, 0, 952, 711);
    }// </editor-fold>//GEN-END:initComponents

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
       r++; 
         if(a2==0)
          {
             if(q%2==0)
             {
                 b62.setBackground(Color.red);
                 q++;
                 a2++;
                 r62=1;
             }
             else
             {
                  b62.setBackground(Color.blue);
                  q++;a2++;
                  r62=2;
             }
          }
         else if(a2==1)
          {
             if(q%2==0)
             {
                 b52.setBackground(Color.red);
                 q++;
                 a2++;
                 r52=1;
             }
             else
             {
                  b52.setBackground(Color.blue);
                  q++;a2++;
                  r52=2;
             }
          }
         else if(a2==2)
          {
             if(q%2==0)
             {
                 b42.setBackground(Color.red);
                 q++;
                 a2++;
                 r42=1;
             }
             else
             {
                  b42.setBackground(Color.blue);
                  q++;a2++;
                  r42=2;
             }
          }
         else if(a2==3)
          {
             if(q%2==0)
             {
                 b32.setBackground(Color.red);
                 q++;
                 a2++;
                 r32=1;
             }
             else
             {
                  b32.setBackground(Color.blue);
                  q++;a2++;
                  r32=2;
             }
          }
         else if(a2==4)
          {
             if(q%2==0)
             {
                 b22.setBackground(Color.red);
                 q++;
                 a2++;
                 r22=1;
             }
             else
             {
                  b22.setBackground(Color.blue);
                  q++;a2++;
                  r22=2;
             }
          }  
         else if(a2==5)
          {
             if(q%2==0)
             {
                 b12.setBackground(Color.red);
                 q++;
                 a2++;
                 r12=1;
             }
             else
             {
                  b12.setBackground(Color.blue);
                  q++;a2++;
                  r12=2;
             }
          } 
           if(((r11==1)&&(r12==1)&&(r13==1)&&(r14==1))||((r12==1)&&(r13==1)&&(r14==1)&&(r15==1))||((r13==1)&&(r14==1)&&(r15==1)&&(r16==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else  if(((r21==1)&&(r22==1)&&(r23==1)&&(r24==1))||((r22==1)&&(r23==1)&&(r24==1)&&(r25==1))||((r23==1)&&(r24==1)&&(r25==1)&&(r26==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r31==1)&&(r32==1)&&(r33==1)&&(r34==1))||((r32==1)&&(r33==1)&&(r34==1)&&(r35==1))||((r33==1)&&(r34==1)&&(r35==1)&&(r36==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
         
          else if(((r41==1)&&(r42==1)&&(r43==1)&&(r44==1))||((r42==1)&&(r43==1)&&(r44==1)&&(r45==1))||((r43==1)&&(r44==1)&&(r45==1)&&(r46==1)))
          {
            ms="Red won the Match";
           
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if(((r51==1)&&(r52==1)&&(r53==1)&&(r54==1))||((r52==1)&&(r53==1)&&(r54==1)&&(r55==1))||((r53==1)&&(r54==1)&&(r55==1)&&(r56==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==1)&&(r62==1)&&(r63==1)&&(r64==1))||((r62==1)&&(r63==1)&&(r64==1)&&(r65==1))||((r63==1)&&(r64==1)&&(r65==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==1)&&(r21==1)&&(r31==1)&&(r41==1))||((r21==1)&&(r31==1)&&(r41==1)&&(r51==1))||((r31==1)&&(r41==1)&&(r51==1)&&(r61==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==1)&&(r22==1)&&(r32==1)&&(r42==1))||((r22==1)&&(r32==1)&&(r42==1)&&(r52==1))||((r32==1)&&(r42==1)&&(r52==1)&&(r62==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==1)&&(r23==1)&&(r33==1)&&(r43==1))||((r23==1)&&(r33==1)&&(r43==1)&&(r53==1))||((r33==1)&&(r43==1)&&(r53==1)&&(r63==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==1)&&(r24==1)&&(r34==1)&&(r44==1))||((r24==1)&&(r34==1)&&(r44==1)&&(r54==1))||((r34==1)&&(r44==1)&&(r54==1)&&(r64==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==1)&&(r25==1)&&(r35==1)&&(r45==1))||((r25==1)&&(r35==1)&&(r45==1)&&(r55==1))||((r35==1)&&(r45==1)&&(r55==1)&&(r65==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==1)&&(r26==1)&&(r36==1)&&(r46==1))||((r26==1)&&(r36==1)&&(r46==1)&&(r56==1))||((r36==1)&&(r46==1)&&(r56==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==1)&&(r32==1)&&(r23==1)&&(r14==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==1)&&(r42==1)&&(r33==1)&&(r24==1))||((r42==1)&&(r33==1)&&(r24==1)&&(r15==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==1)&&(r52==1)&&(r43==1)&&(r34==1))||((r52==1)&&(r43==1)&&(r34==1)&&(r25==1))||((r43==1)&&(r34==1)&&(r25==1)&&(r16==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==1)&&(r53==1)&&(r44==1)&&(r35==1))||((r53==1)&&(r44==1)&&(r35==1)&&(r26==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==1)&&(r54==1)&&(r45==1)&&(r36==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==1)&&(r24==1)&&(r35==1)&&(r46==1))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==1)&&(r23==1)&&(r34==1)&&(r45==1))||((r23==1)&&(r34==1)&&(r45==1)&&(r56==1)))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==1)&&(r22==1)&&(r33==1)&&(r44==1))||((r22==1)&&(r33==1)&&(r44==1)&&(r55==1))||((r33==1)&&(r44==1)&&(r55==1)&&(r66==1)))
           {
               ms="Red won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==1)&&(r32==1)&&(r43==1)&&(r54==1))||((r32==1)&&(r43==1)&&(r54==1)&&(r65==1)))
          {
             ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==1)&&(r42==1)&&(r53==1)&&(r64==1))
          {
               ms="Red won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r12==2)&&(r13==2)&&(r14==2))||((r12==2)&&(r13==2)&&(r14==2)&&(r15==2))||((r13==2)&&(r14==2)&&(r15==2)&&(r16==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r21==2)&&(r22==2)&&(r23==2)&&(r24==2))||((r22==2)&&(r23==2)&&(r24==2)&&(r25==2))||((r23==2)&&(r24==2)&&(r25==2)&&(r26==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         else if(((r31==2)&&(r32==2)&&(r33==2)&&(r34==2))||((r32==2)&&(r33==2)&&(r34==2)&&(r35==2))||((r33==2)&&(r34==2)&&(r35==2)&&(r36==2)))
          {
                ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r41==2)&&(r42==2)&&(r43==2)&&(r44==2))||((r42==2)&&(r43==2)&&(r44==2)&&(r45==2))||((r43==2)&&(r44==2)&&(r45==2)&&(r46==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r52==2)&&(r53==2)&&(r54==2))||((r52==2)&&(r53==2)&&(r54==2)&&(r55==2))||((r53==2)&&(r54==2)&&(r55==2)&&(r56==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==2)&&(r62==2)&&(r63==2)&&(r64==2))||((r62==2)&&(r63==2)&&(r64==2)&&(r65==2))||((r63==2)&&(r64==2)&&(r65==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==2)&&(r21==2)&&(r31==2)&&(r41==2))||((r21==2)&&(r31==2)&&(r41==2)&&(r51==2))||((r31==2)&&(r41==2)&&(r51==2)&&(r61==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==2)&&(r22==2)&&(r32==2)&&(r42==2))||((r22==2)&&(r32==2)&&(r42==2)&&(r52==2))||((r32==2)&&(r42==2)&&(r52==2)&&(r62==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==2)&&(r23==2)&&(r33==2)&&(r43==2))||((r23==2)&&(r33==2)&&(r43==2)&&(r53==2))||((r33==2)&&(r43==2)&&(r53==2)&&(r63==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==2)&&(r24==2)&&(r34==2)&&(r44==2))||((r24==2)&&(r34==2)&&(r44==2)&&(r54==2))||((r34==2)&&(r44==2)&&(r54==2)&&(r64==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==2)&&(r25==2)&&(r35==2)&&(r45==2))||((r25==2)&&(r35==2)&&(r45==2)&&(r55==2))||((r35==2)&&(r45==2)&&(r55==2)&&(r65==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==2)&&(r26==2)&&(r36==2)&&(r46==2))||((r26==2)&&(r36==2)&&(r46==2)&&(r56==2))||((r36==2)&&(r46==2)&&(r56==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==2)&&(r32==2)&&(r23==2)&&(r14==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r42==2)&&(r33==2)&&(r24==2))||((r42==2)&&(r33==2)&&(r24==2)&&(r15==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==2)&&(r52==2)&&(r43==2)&&(r34==2))||((r52==2)&&(r43==2)&&(r34==2)&&(r25==2))||((r43==2)&&(r34==2)&&(r25==2)&&(r16==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==2)&&(r53==2)&&(r44==2)&&(r35==2))||((r53==2)&&(r44==2)&&(r35==2)&&(r26==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==2)&&(r54==2)&&(r45==2)&&(r36==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==2)&&(r24==2)&&(r35==2)&&(r46==2))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==2)&&(r23==2)&&(r34==2)&&(r45==2))||((r23==2)&&(r34==2)&&(r45==2)&&(r56==2)))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r22==2)&&(r33==2)&&(r44==2))||((r22==2)&&(r33==2)&&(r44==2)&&(r55==2))||((r33==2)&&(r44==2)&&(r55==2)&&(r66==2)))
           {
               ms="Blue won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==2)&&(r32==2)&&(r43==2)&&(r54==2))||((r32==2)&&(r43==2)&&(r54==2)&&(r65==2)))
          {
             ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==2)&&(r42==2)&&(r53==2)&&(r64==2))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(r==36)
          {
              ms="Match is Draw";
              game12 g12=new game12(ms);
              g12.setVisible(true);
          }
    }//GEN-LAST:event_c2ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        r++; 
         if(a1==0)
          {
             if(q%2==0)
             {
                 b61.setBackground(Color.red);
                 q++;
                 a1++;
                 r61=1;
             }
             else
             {
                  b61.setBackground(Color.blue);
                  q++;a1++;
                  r61=2;
             }
          }
         else if(a1==1)
          {
             if(q%2==0)
             {
                 b51.setBackground(Color.red);
                 q++;
                 a1++;
                 r51=1;
             }
             else
             {
                  b51.setBackground(Color.blue);
                  q++;a1++;
                  r51=2;
             }
          }
         else if(a1==2)
          {
             if(q%2==0)
             {
                 b41.setBackground(Color.red);
                 q++;
                 a1++;
                 r41=1;
             }
             else
             {
                  b41.setBackground(Color.blue);
                  q++;a1++;
                  r41=2;
             }
          }
         else if(a1==3)
          {
             if(q%2==0)
             {
                 b31.setBackground(Color.red);
                 q++;
                 a1++;
                 r31=1;
             }
             else
             {
                  b31.setBackground(Color.blue);
                  q++;a1++;
                  r31=2;
             }
          }
         else if(a1==4)
          {
             if(q%2==0)
             {
                 b21.setBackground(Color.red);
                 q++;
                 a1++;
                 r21=1;
             }
             else
             {
                  b21.setBackground(Color.blue);
                  q++;a1++;
                  r21=2;
             }
          }  
         else if(a1==5)
          {
             if(q%2==0)
             {
                 b11.setBackground(Color.red);
                 q++;
                 a1++;
                 r11=1;
             }
             else
             {
                  b11.setBackground(Color.blue);
                  q++;a1++;
                  r11=2;
             }
          }
            if(((r11==1)&&(r12==1)&&(r13==1)&&(r14==1))||((r12==1)&&(r13==1)&&(r14==1)&&(r15==1))||((r13==1)&&(r14==1)&&(r15==1)&&(r16==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else  if(((r21==1)&&(r22==1)&&(r23==1)&&(r24==1))||((r22==1)&&(r23==1)&&(r24==1)&&(r25==1))||((r23==1)&&(r24==1)&&(r25==1)&&(r26==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r31==1)&&(r32==1)&&(r33==1)&&(r34==1))||((r32==1)&&(r33==1)&&(r34==1)&&(r35==1))||((r33==1)&&(r34==1)&&(r35==1)&&(r36==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
         
          else if(((r41==1)&&(r42==1)&&(r43==1)&&(r44==1))||((r42==1)&&(r43==1)&&(r44==1)&&(r45==1))||((r43==1)&&(r44==1)&&(r45==1)&&(r46==1)))
          {
            ms="Red won the Match";
           
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if(((r51==1)&&(r52==1)&&(r53==1)&&(r54==1))||((r52==1)&&(r53==1)&&(r54==1)&&(r55==1))||((r53==1)&&(r54==1)&&(r55==1)&&(r56==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==1)&&(r62==1)&&(r63==1)&&(r64==1))||((r62==1)&&(r63==1)&&(r64==1)&&(r65==1))||((r63==1)&&(r64==1)&&(r65==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==1)&&(r21==1)&&(r31==1)&&(r41==1))||((r21==1)&&(r31==1)&&(r41==1)&&(r51==1))||((r31==1)&&(r41==1)&&(r51==1)&&(r61==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==1)&&(r22==1)&&(r32==1)&&(r42==1))||((r22==1)&&(r32==1)&&(r42==1)&&(r52==1))||((r32==1)&&(r42==1)&&(r52==1)&&(r62==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==1)&&(r23==1)&&(r33==1)&&(r43==1))||((r23==1)&&(r33==1)&&(r43==1)&&(r53==1))||((r33==1)&&(r43==1)&&(r53==1)&&(r63==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==1)&&(r24==1)&&(r34==1)&&(r44==1))||((r24==1)&&(r34==1)&&(r44==1)&&(r54==1))||((r34==1)&&(r44==1)&&(r54==1)&&(r64==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==1)&&(r25==1)&&(r35==1)&&(r45==1))||((r25==1)&&(r35==1)&&(r45==1)&&(r55==1))||((r35==1)&&(r45==1)&&(r55==1)&&(r65==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==1)&&(r26==1)&&(r36==1)&&(r46==1))||((r26==1)&&(r36==1)&&(r46==1)&&(r56==1))||((r36==1)&&(r46==1)&&(r56==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==1)&&(r32==1)&&(r23==1)&&(r14==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==1)&&(r42==1)&&(r33==1)&&(r24==1))||((r42==1)&&(r33==1)&&(r24==1)&&(r15==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==1)&&(r52==1)&&(r43==1)&&(r34==1))||((r52==1)&&(r43==1)&&(r34==1)&&(r25==1))||((r43==1)&&(r34==1)&&(r25==1)&&(r16==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==1)&&(r53==1)&&(r44==1)&&(r35==1))||((r53==1)&&(r44==1)&&(r35==1)&&(r26==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==1)&&(r54==1)&&(r45==1)&&(r36==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==1)&&(r24==1)&&(r35==1)&&(r46==1))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==1)&&(r23==1)&&(r34==1)&&(r45==1))||((r23==1)&&(r34==1)&&(r45==1)&&(r56==1)))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==1)&&(r22==1)&&(r33==1)&&(r44==1))||((r22==1)&&(r33==1)&&(r44==1)&&(r55==1))||((r33==1)&&(r44==1)&&(r55==1)&&(r66==1)))
           {
               ms="Red won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==1)&&(r32==1)&&(r43==1)&&(r54==1))||((r32==1)&&(r43==1)&&(r54==1)&&(r65==1)))
          {
             ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==1)&&(r42==1)&&(r53==1)&&(r64==1))
          {
               ms="Red won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r12==2)&&(r13==2)&&(r14==2))||((r12==2)&&(r13==2)&&(r14==2)&&(r15==2))||((r13==2)&&(r14==2)&&(r15==2)&&(r16==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r21==2)&&(r22==2)&&(r23==2)&&(r24==2))||((r22==2)&&(r23==2)&&(r24==2)&&(r25==2))||((r23==2)&&(r24==2)&&(r25==2)&&(r26==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         else if(((r31==2)&&(r32==2)&&(r33==2)&&(r34==2))||((r32==2)&&(r33==2)&&(r34==2)&&(r35==2))||((r33==2)&&(r34==2)&&(r35==2)&&(r36==2)))
          {
                ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r41==2)&&(r42==2)&&(r43==2)&&(r44==2))||((r42==2)&&(r43==2)&&(r44==2)&&(r45==2))||((r43==2)&&(r44==2)&&(r45==2)&&(r46==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r52==2)&&(r53==2)&&(r54==2))||((r52==2)&&(r53==2)&&(r54==2)&&(r55==2))||((r53==2)&&(r54==2)&&(r55==2)&&(r56==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==2)&&(r62==2)&&(r63==2)&&(r64==2))||((r62==2)&&(r63==2)&&(r64==2)&&(r65==2))||((r63==2)&&(r64==2)&&(r65==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==2)&&(r21==2)&&(r31==2)&&(r41==2))||((r21==2)&&(r31==2)&&(r41==2)&&(r51==2))||((r31==2)&&(r41==2)&&(r51==2)&&(r61==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==2)&&(r22==2)&&(r32==2)&&(r42==2))||((r22==2)&&(r32==2)&&(r42==2)&&(r52==2))||((r32==2)&&(r42==2)&&(r52==2)&&(r62==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==2)&&(r23==2)&&(r33==2)&&(r43==2))||((r23==2)&&(r33==2)&&(r43==2)&&(r53==2))||((r33==2)&&(r43==2)&&(r53==2)&&(r63==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==2)&&(r24==2)&&(r34==2)&&(r44==2))||((r24==2)&&(r34==2)&&(r44==2)&&(r54==2))||((r34==2)&&(r44==2)&&(r54==2)&&(r64==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==2)&&(r25==2)&&(r35==2)&&(r45==2))||((r25==2)&&(r35==2)&&(r45==2)&&(r55==2))||((r35==2)&&(r45==2)&&(r55==2)&&(r65==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==2)&&(r26==2)&&(r36==2)&&(r46==2))||((r26==2)&&(r36==2)&&(r46==2)&&(r56==2))||((r36==2)&&(r46==2)&&(r56==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==2)&&(r32==2)&&(r23==2)&&(r14==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r42==2)&&(r33==2)&&(r24==2))||((r42==2)&&(r33==2)&&(r24==2)&&(r15==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==2)&&(r52==2)&&(r43==2)&&(r34==2))||((r52==2)&&(r43==2)&&(r34==2)&&(r25==2))||((r43==2)&&(r34==2)&&(r25==2)&&(r16==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==2)&&(r53==2)&&(r44==2)&&(r35==2))||((r53==2)&&(r44==2)&&(r35==2)&&(r26==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==2)&&(r54==2)&&(r45==2)&&(r36==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==2)&&(r24==2)&&(r35==2)&&(r46==2))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==2)&&(r23==2)&&(r34==2)&&(r45==2))||((r23==2)&&(r34==2)&&(r45==2)&&(r56==2)))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r22==2)&&(r33==2)&&(r44==2))||((r22==2)&&(r33==2)&&(r44==2)&&(r55==2))||((r33==2)&&(r44==2)&&(r55==2)&&(r66==2)))
           {
               ms="Blue won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==2)&&(r32==2)&&(r43==2)&&(r54==2))||((r32==2)&&(r43==2)&&(r54==2)&&(r65==2)))
          {
             ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==2)&&(r42==2)&&(r53==2)&&(r64==2))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
               g12.setVisible(true);
          }
          else if(r==36)
          {
              ms="Match is Draw";
              game12 g12=new game12(ms);
              g12.setVisible(true);
          }
    }//GEN-LAST:event_c1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        r++; 
         if(a3==0)
          {
             if(q%2==0)
             {
                 b63.setBackground(Color.red);
                 q++;
                 a3++;
                 r63=1;
             }
             else
             {
                  b63.setBackground(Color.blue);
                  q++;a3++;
                  r63=2;
             }
          }
         else if(a3==1)
          {
             if(q%2==0)
             {
                 b53.setBackground(Color.red);
                 q++;
                 a3++;
                 r53=1;
             }
             else
             {
                  b53.setBackground(Color.blue);
                  q++;a3++;
                  r53=2;
             }
          }
         else if(a3==2)
          {
             if(q%2==0)
             {
                 b43.setBackground(Color.red);
                 q++;
                 a3++;
                 r43=1;
             }
             else
             {
                  b43.setBackground(Color.blue);
                  q++;a3++;
                  r43=2;
             }
          }
         else if(a3==3)
          {
             if(q%2==0)
             {
                 b33.setBackground(Color.red);
                 q++;
                 a3++;
                 r33=1;
             }
             else
             {
                  b33.setBackground(Color.blue);
                  q++;a3++;
                  r33=2;
             }
          }
         else if(a3==4)
          {
             if(q%2==0)
             {
                 b23.setBackground(Color.red);
                 q++;
                 a3++;
                 r23=1;
             }
             else
             {
                  b23.setBackground(Color.blue);
                  q++;a3++;
                  r23=2;
             }
          }  
         else if(a3==5)
          {
             if(q%2==0)
             {
                 b13.setBackground(Color.red);
                 q++;
                 a3++;
                 r13=1;
             }
             else
             {
                  b13.setBackground(Color.blue);
                  q++;a3++;
                  r13=2;
             }
          } 
           if(((r11==1)&&(r12==1)&&(r13==1)&&(r14==1))||((r12==1)&&(r13==1)&&(r14==1)&&(r15==1))||((r13==1)&&(r14==1)&&(r15==1)&&(r16==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else  if(((r21==1)&&(r22==1)&&(r23==1)&&(r24==1))||((r22==1)&&(r23==1)&&(r24==1)&&(r25==1))||((r23==1)&&(r24==1)&&(r25==1)&&(r26==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r31==1)&&(r32==1)&&(r33==1)&&(r34==1))||((r32==1)&&(r33==1)&&(r34==1)&&(r35==1))||((r33==1)&&(r34==1)&&(r35==1)&&(r36==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
         
          else if(((r41==1)&&(r42==1)&&(r43==1)&&(r44==1))||((r42==1)&&(r43==1)&&(r44==1)&&(r45==1))||((r43==1)&&(r44==1)&&(r45==1)&&(r46==1)))
          {
            ms="Red won the Match";
           
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if(((r51==1)&&(r52==1)&&(r53==1)&&(r54==1))||((r52==1)&&(r53==1)&&(r54==1)&&(r55==1))||((r53==1)&&(r54==1)&&(r55==1)&&(r56==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==1)&&(r62==1)&&(r63==1)&&(r64==1))||((r62==1)&&(r63==1)&&(r64==1)&&(r65==1))||((r63==1)&&(r64==1)&&(r65==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==1)&&(r21==1)&&(r31==1)&&(r41==1))||((r21==1)&&(r31==1)&&(r41==1)&&(r51==1))||((r31==1)&&(r41==1)&&(r51==1)&&(r61==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==1)&&(r22==1)&&(r32==1)&&(r42==1))||((r22==1)&&(r32==1)&&(r42==1)&&(r52==1))||((r32==1)&&(r42==1)&&(r52==1)&&(r62==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==1)&&(r23==1)&&(r33==1)&&(r43==1))||((r23==1)&&(r33==1)&&(r43==1)&&(r53==1))||((r33==1)&&(r43==1)&&(r53==1)&&(r63==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==1)&&(r24==1)&&(r34==1)&&(r44==1))||((r24==1)&&(r34==1)&&(r44==1)&&(r54==1))||((r34==1)&&(r44==1)&&(r54==1)&&(r64==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==1)&&(r25==1)&&(r35==1)&&(r45==1))||((r25==1)&&(r35==1)&&(r45==1)&&(r55==1))||((r35==1)&&(r45==1)&&(r55==1)&&(r65==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==1)&&(r26==1)&&(r36==1)&&(r46==1))||((r26==1)&&(r36==1)&&(r46==1)&&(r56==1))||((r36==1)&&(r46==1)&&(r56==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==1)&&(r32==1)&&(r23==1)&&(r14==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==1)&&(r42==1)&&(r33==1)&&(r24==1))||((r42==1)&&(r33==1)&&(r24==1)&&(r15==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==1)&&(r52==1)&&(r43==1)&&(r34==1))||((r52==1)&&(r43==1)&&(r34==1)&&(r25==1))||((r43==1)&&(r34==1)&&(r25==1)&&(r16==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==1)&&(r53==1)&&(r44==1)&&(r35==1))||((r53==1)&&(r44==1)&&(r35==1)&&(r26==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==1)&&(r54==1)&&(r45==1)&&(r36==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==1)&&(r24==1)&&(r35==1)&&(r46==1))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==1)&&(r23==1)&&(r34==1)&&(r45==1))||((r23==1)&&(r34==1)&&(r45==1)&&(r56==1)))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==1)&&(r22==1)&&(r33==1)&&(r44==1))||((r22==1)&&(r33==1)&&(r44==1)&&(r55==1))||((r33==1)&&(r44==1)&&(r55==1)&&(r66==1)))
           {
               ms="Red won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==1)&&(r32==1)&&(r43==1)&&(r54==1))||((r32==1)&&(r43==1)&&(r54==1)&&(r65==1)))
          {
             ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==1)&&(r42==1)&&(r53==1)&&(r64==1))
          {
               ms="Red won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r12==2)&&(r13==2)&&(r14==2))||((r12==2)&&(r13==2)&&(r14==2)&&(r15==2))||((r13==2)&&(r14==2)&&(r15==2)&&(r16==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r21==2)&&(r22==2)&&(r23==2)&&(r24==2))||((r22==2)&&(r23==2)&&(r24==2)&&(r25==2))||((r23==2)&&(r24==2)&&(r25==2)&&(r26==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         else if(((r31==2)&&(r32==2)&&(r33==2)&&(r34==2))||((r32==2)&&(r33==2)&&(r34==2)&&(r35==2))||((r33==2)&&(r34==2)&&(r35==2)&&(r36==2)))
          {
                ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r41==2)&&(r42==2)&&(r43==2)&&(r44==2))||((r42==2)&&(r43==2)&&(r44==2)&&(r45==2))||((r43==2)&&(r44==2)&&(r45==2)&&(r46==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r52==2)&&(r53==2)&&(r54==2))||((r52==2)&&(r53==2)&&(r54==2)&&(r55==2))||((r53==2)&&(r54==2)&&(r55==2)&&(r56==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==2)&&(r62==2)&&(r63==2)&&(r64==2))||((r62==2)&&(r63==2)&&(r64==2)&&(r65==2))||((r63==2)&&(r64==2)&&(r65==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==2)&&(r21==2)&&(r31==2)&&(r41==2))||((r21==2)&&(r31==2)&&(r41==2)&&(r51==2))||((r31==2)&&(r41==2)&&(r51==2)&&(r61==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==2)&&(r22==2)&&(r32==2)&&(r42==2))||((r22==2)&&(r32==2)&&(r42==2)&&(r52==2))||((r32==2)&&(r42==2)&&(r52==2)&&(r62==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==2)&&(r23==2)&&(r33==2)&&(r43==2))||((r23==2)&&(r33==2)&&(r43==2)&&(r53==2))||((r33==2)&&(r43==2)&&(r53==2)&&(r63==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==2)&&(r24==2)&&(r34==2)&&(r44==2))||((r24==2)&&(r34==2)&&(r44==2)&&(r54==2))||((r34==2)&&(r44==2)&&(r54==2)&&(r64==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==2)&&(r25==2)&&(r35==2)&&(r45==2))||((r25==2)&&(r35==2)&&(r45==2)&&(r55==2))||((r35==2)&&(r45==2)&&(r55==2)&&(r65==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==2)&&(r26==2)&&(r36==2)&&(r46==2))||((r26==2)&&(r36==2)&&(r46==2)&&(r56==2))||((r36==2)&&(r46==2)&&(r56==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==2)&&(r32==2)&&(r23==2)&&(r14==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r42==2)&&(r33==2)&&(r24==2))||((r42==2)&&(r33==2)&&(r24==2)&&(r15==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==2)&&(r52==2)&&(r43==2)&&(r34==2))||((r52==2)&&(r43==2)&&(r34==2)&&(r25==2))||((r43==2)&&(r34==2)&&(r25==2)&&(r16==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==2)&&(r53==2)&&(r44==2)&&(r35==2))||((r53==2)&&(r44==2)&&(r35==2)&&(r26==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==2)&&(r54==2)&&(r45==2)&&(r36==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==2)&&(r24==2)&&(r35==2)&&(r46==2))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==2)&&(r23==2)&&(r34==2)&&(r45==2))||((r23==2)&&(r34==2)&&(r45==2)&&(r56==2)))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r22==2)&&(r33==2)&&(r44==2))||((r22==2)&&(r33==2)&&(r44==2)&&(r55==2))||((r33==2)&&(r44==2)&&(r55==2)&&(r66==2)))
           {
               ms="Blue won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==2)&&(r32==2)&&(r43==2)&&(r54==2))||((r32==2)&&(r43==2)&&(r54==2)&&(r65==2)))
          {
             ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==2)&&(r42==2)&&(r53==2)&&(r64==2))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(r==36)
          {
              ms="Match is Draw";
              game12 g12=new game12(ms);
              g12.setVisible(true);
          }
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        r++; 
         if(a4==0)
          {
             if(q%2==0)
             {
                 b64.setBackground(Color.red);
                 q++;
                 a4++;
                 r64=1;
             }
             else
             {
                  b64.setBackground(Color.blue);
                  q++;a4++;
                  r64=2;
             }
          }
         else if(a4==1)
          {
             if(q%2==0)
             {
                 b54.setBackground(Color.red);
                 q++;
                 a4++;
                 r54=1;
             }
             else
             {
                  b54.setBackground(Color.blue);
                  q++;a4++;
                  r54=2;
             }
          }
         else if(a4==2)
          {
             if(q%2==0)
             {
                 b44.setBackground(Color.red);
                 q++;
                 a4++;
                 r44=1;
             }
             else
             {
                  b44.setBackground(Color.blue);
                  q++;a4++;
                  r44=2;
             }
          }
         else if(a4==3)
          {
             if(q%2==0)
             {
                 b34.setBackground(Color.red);
                 q++;
                 a4++;
                 r34=1;
             }
             else
             {
                  b34.setBackground(Color.blue);
                  q++;a4++;
                  r34=2;
             }
          }
         else if(a4==4)
          {
             if(q%2==0)
             {
                 b24.setBackground(Color.red);
                 q++;
                 a4++;
                 r24=1;
             }
             
             else
             {
                  b24.setBackground(Color.blue);
                  q++;a4++;
                  r24=2;
             }
          }  
         else if(a4==5)
          {
             if(q%2==0)
             {
                 b14.setBackground(Color.red);
                 q++;
                 a4++;
                 r14=1;
             }
             else
             {
                  b14.setBackground(Color.blue);
                  q++;a4++;
                  r14=2;
             }
          } 
           if(((r11==1)&&(r12==1)&&(r13==1)&&(r14==1))||((r12==1)&&(r13==1)&&(r14==1)&&(r15==1))||((r13==1)&&(r14==1)&&(r15==1)&&(r16==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else  if(((r21==1)&&(r22==1)&&(r23==1)&&(r24==1))||((r22==1)&&(r23==1)&&(r24==1)&&(r25==1))||((r23==1)&&(r24==1)&&(r25==1)&&(r26==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r31==1)&&(r32==1)&&(r33==1)&&(r34==1))||((r32==1)&&(r33==1)&&(r34==1)&&(r35==1))||((r33==1)&&(r34==1)&&(r35==1)&&(r36==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
         
          else if(((r41==1)&&(r42==1)&&(r43==1)&&(r44==1))||((r42==1)&&(r43==1)&&(r44==1)&&(r45==1))||((r43==1)&&(r44==1)&&(r45==1)&&(r46==1)))
          {
            ms="Red won the Match";
           
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if(((r51==1)&&(r52==1)&&(r53==1)&&(r54==1))||((r52==1)&&(r53==1)&&(r54==1)&&(r55==1))||((r53==1)&&(r54==1)&&(r55==1)&&(r56==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==1)&&(r62==1)&&(r63==1)&&(r64==1))||((r62==1)&&(r63==1)&&(r64==1)&&(r65==1))||((r63==1)&&(r64==1)&&(r65==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==1)&&(r21==1)&&(r31==1)&&(r41==1))||((r21==1)&&(r31==1)&&(r41==1)&&(r51==1))||((r31==1)&&(r41==1)&&(r51==1)&&(r61==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==1)&&(r22==1)&&(r32==1)&&(r42==1))||((r22==1)&&(r32==1)&&(r42==1)&&(r52==1))||((r32==1)&&(r42==1)&&(r52==1)&&(r62==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==1)&&(r23==1)&&(r33==1)&&(r43==1))||((r23==1)&&(r33==1)&&(r43==1)&&(r53==1))||((r33==1)&&(r43==1)&&(r53==1)&&(r63==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==1)&&(r24==1)&&(r34==1)&&(r44==1))||((r24==1)&&(r34==1)&&(r44==1)&&(r54==1))||((r34==1)&&(r44==1)&&(r54==1)&&(r64==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==1)&&(r25==1)&&(r35==1)&&(r45==1))||((r25==1)&&(r35==1)&&(r45==1)&&(r55==1))||((r35==1)&&(r45==1)&&(r55==1)&&(r65==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==1)&&(r26==1)&&(r36==1)&&(r46==1))||((r26==1)&&(r36==1)&&(r46==1)&&(r56==1))||((r36==1)&&(r46==1)&&(r56==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==1)&&(r32==1)&&(r23==1)&&(r14==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==1)&&(r42==1)&&(r33==1)&&(r24==1))||((r42==1)&&(r33==1)&&(r24==1)&&(r15==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==1)&&(r52==1)&&(r43==1)&&(r34==1))||((r52==1)&&(r43==1)&&(r34==1)&&(r25==1))||((r43==1)&&(r34==1)&&(r25==1)&&(r16==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==1)&&(r53==1)&&(r44==1)&&(r35==1))||((r53==1)&&(r44==1)&&(r35==1)&&(r26==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==1)&&(r54==1)&&(r45==1)&&(r36==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==1)&&(r24==1)&&(r35==1)&&(r46==1))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==1)&&(r23==1)&&(r34==1)&&(r45==1))||((r23==1)&&(r34==1)&&(r45==1)&&(r56==1)))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==1)&&(r22==1)&&(r33==1)&&(r44==1))||((r22==1)&&(r33==1)&&(r44==1)&&(r55==1))||((r33==1)&&(r44==1)&&(r55==1)&&(r66==1)))
           {
               ms="Red won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==1)&&(r32==1)&&(r43==1)&&(r54==1))||((r32==1)&&(r43==1)&&(r54==1)&&(r65==1)))
          {
             ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==1)&&(r42==1)&&(r53==1)&&(r64==1))
          {
               ms="Red won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r12==2)&&(r13==2)&&(r14==2))||((r12==2)&&(r13==2)&&(r14==2)&&(r15==2))||((r13==2)&&(r14==2)&&(r15==2)&&(r16==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r21==2)&&(r22==2)&&(r23==2)&&(r24==2))||((r22==2)&&(r23==2)&&(r24==2)&&(r25==2))||((r23==2)&&(r24==2)&&(r25==2)&&(r26==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         else if(((r31==2)&&(r32==2)&&(r33==2)&&(r34==2))||((r32==2)&&(r33==2)&&(r34==2)&&(r35==2))||((r33==2)&&(r34==2)&&(r35==2)&&(r36==2)))
          {
                ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r41==2)&&(r42==2)&&(r43==2)&&(r44==2))||((r42==2)&&(r43==2)&&(r44==2)&&(r45==2))||((r43==2)&&(r44==2)&&(r45==2)&&(r46==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r52==2)&&(r53==2)&&(r54==2))||((r52==2)&&(r53==2)&&(r54==2)&&(r55==2))||((r53==2)&&(r54==2)&&(r55==2)&&(r56==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==2)&&(r62==2)&&(r63==2)&&(r64==2))||((r62==2)&&(r63==2)&&(r64==2)&&(r65==2))||((r63==2)&&(r64==2)&&(r65==2)&&(r66==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==2)&&(r21==2)&&(r31==2)&&(r41==2))||((r21==2)&&(r31==2)&&(r41==2)&&(r51==2))||((r31==2)&&(r41==2)&&(r51==2)&&(r61==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==2)&&(r22==2)&&(r32==2)&&(r42==2))||((r22==2)&&(r32==2)&&(r42==2)&&(r52==2))||((r32==2)&&(r42==2)&&(r52==2)&&(r62==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==2)&&(r23==2)&&(r33==2)&&(r43==2))||((r23==2)&&(r33==2)&&(r43==2)&&(r53==2))||((r33==2)&&(r43==2)&&(r53==2)&&(r63==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==2)&&(r24==2)&&(r34==2)&&(r44==2))||((r24==2)&&(r34==2)&&(r44==2)&&(r54==2))||((r34==2)&&(r44==2)&&(r54==2)&&(r64==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==2)&&(r25==2)&&(r35==2)&&(r45==2))||((r25==2)&&(r35==2)&&(r45==2)&&(r55==2))||((r35==2)&&(r45==2)&&(r55==2)&&(r65==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==2)&&(r26==2)&&(r36==2)&&(r46==2))||((r26==2)&&(r36==2)&&(r46==2)&&(r56==2))||((r36==2)&&(r46==2)&&(r56==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==2)&&(r32==2)&&(r23==2)&&(r14==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r42==2)&&(r33==2)&&(r24==2))||((r42==2)&&(r33==2)&&(r24==2)&&(r15==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==2)&&(r52==2)&&(r43==2)&&(r34==2))||((r52==2)&&(r43==2)&&(r34==2)&&(r25==2))||((r43==2)&&(r34==2)&&(r25==2)&&(r16==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==2)&&(r53==2)&&(r44==2)&&(r35==2))||((r53==2)&&(r44==2)&&(r35==2)&&(r26==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==2)&&(r54==2)&&(r45==2)&&(r36==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==2)&&(r24==2)&&(r35==2)&&(r46==2))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==2)&&(r23==2)&&(r34==2)&&(r45==2))||((r23==2)&&(r34==2)&&(r45==2)&&(r56==2)))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r22==2)&&(r33==2)&&(r44==2))||((r22==2)&&(r33==2)&&(r44==2)&&(r55==2))||((r33==2)&&(r44==2)&&(r55==2)&&(r66==2)))
           {
               ms="Blue won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==2)&&(r32==2)&&(r43==2)&&(r54==2))||((r32==2)&&(r43==2)&&(r54==2)&&(r65==2)))
          {
             ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==2)&&(r42==2)&&(r53==2)&&(r64==2))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(r==36)
          {
              ms="Match is Draw";
              game12 g12=new game12(ms);
              g12.setVisible(true);
          }
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
       r++; 
         if(a5==0)
          {
             if(q%2==0)
             {
                 b65.setBackground(Color.red);
                 q++;
                 a5++;
                 r65=1;
             }
             else
             {
                  b65.setBackground(Color.blue);
                  q++;a5++;
                  r65=2;
             }
          }
         else if(a5==1)
          {
             if(q%2==0)
             {
                 b55.setBackground(Color.red);
                 q++;
                 a5++;
                 r55=1;
             }
             else
             {
                  b55.setBackground(Color.blue);
                  q++;a5++;
                  r55=2;
             }
          }
         else if(a5==2)
          {
             if(q%2==0)
             {
                 b45.setBackground(Color.red);
                 q++;
                 a5++;
                 r45=1;
             }
             else
             {
                  b45.setBackground(Color.blue);
                  q++;a5++;
                  r45=2;
             }
          }
         else if(a5==3)
          {
             if(q%2==0)
             {
                 b35.setBackground(Color.red);
                 q++;
                 a5++;
                 r35=1;
             }
             else
             {
                  b35.setBackground(Color.blue);
                  q++;a5++;
                  r35=2;
             }
          }
         else if(a5==4)
          {
             if(q%2==0)
             {
                 b25.setBackground(Color.red);
                 q++;
                 a5++;
                 r25=1;
             }
             else
             {
                  b25.setBackground(Color.blue);
                  q++;a5++;
                  r25=2;
             }
          }  
         else if(a5==5)
          {
             if(q%2==0)
             {
                 b15.setBackground(Color.red);
                 q++;
                 a5++;
                 r15=1;
             }
             else
             {
                  b15.setBackground(Color.blue);
                  q++;a5++;
                  r15=2;
             }
          }
          if(((r11==1)&&(r12==1)&&(r13==1)&&(r14==1))||((r12==1)&&(r13==1)&&(r14==1)&&(r15==1))||((r13==1)&&(r14==1)&&(r15==1)&&(r16==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else  if(((r21==1)&&(r22==1)&&(r23==1)&&(r24==1))||((r22==1)&&(r23==1)&&(r24==1)&&(r25==1))||((r23==1)&&(r24==1)&&(r25==1)&&(r26==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r31==1)&&(r32==1)&&(r33==1)&&(r34==1))||((r32==1)&&(r33==1)&&(r34==1)&&(r35==1))||((r33==1)&&(r34==1)&&(r35==1)&&(r36==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
         
          else if(((r41==1)&&(r42==1)&&(r43==1)&&(r44==1))||((r42==1)&&(r43==1)&&(r44==1)&&(r45==1))||((r43==1)&&(r44==1)&&(r45==1)&&(r46==1)))
          {
            ms="Red won the Match";
           
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if(((r51==1)&&(r52==1)&&(r53==1)&&(r54==1))||((r52==1)&&(r53==1)&&(r54==1)&&(r55==1))||((r53==1)&&(r54==1)&&(r55==1)&&(r56==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==1)&&(r62==1)&&(r63==1)&&(r64==1))||((r62==1)&&(r63==1)&&(r64==1)&&(r65==1))||((r63==1)&&(r64==1)&&(r65==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==1)&&(r21==1)&&(r31==1)&&(r41==1))||((r21==1)&&(r31==1)&&(r41==1)&&(r51==1))||((r31==1)&&(r41==1)&&(r51==1)&&(r61==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==1)&&(r22==1)&&(r32==1)&&(r42==1))||((r22==1)&&(r32==1)&&(r42==1)&&(r52==1))||((r32==1)&&(r42==1)&&(r52==1)&&(r62==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
         else if(((r13==1)&&(r23==1)&&(r33==1)&&(r43==1))||((r23==1)&&(r33==1)&&(r43==1)&&(r53==1))||((r33==1)&&(r43==1)&&(r53==1)&&(r63==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==1)&&(r24==1)&&(r34==1)&&(r44==1))||((r24==1)&&(r34==1)&&(r44==1)&&(r54==1))||((r34==1)&&(r44==1)&&(r54==1)&&(r64==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==1)&&(r25==1)&&(r35==1)&&(r45==1))||((r25==1)&&(r35==1)&&(r45==1)&&(r55==1))||((r35==1)&&(r45==1)&&(r55==1)&&(r65==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==1)&&(r26==1)&&(r36==1)&&(r46==1))||((r26==1)&&(r36==1)&&(r46==1)&&(r56==1))||((r36==1)&&(r46==1)&&(r56==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==1)&&(r32==1)&&(r23==1)&&(r14==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==1)&&(r42==1)&&(r33==1)&&(r24==1))||((r42==1)&&(r33==1)&&(r24==1)&&(r15==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==1)&&(r52==1)&&(r43==1)&&(r34==1))||((r52==1)&&(r43==1)&&(r34==1)&&(r25==1))||((r43==1)&&(r34==1)&&(r25==1)&&(r16==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==1)&&(r53==1)&&(r44==1)&&(r35==1))||((r53==1)&&(r44==1)&&(r35==1)&&(r26==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==1)&&(r54==1)&&(r45==1)&&(r36==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==1)&&(r24==1)&&(r35==1)&&(r46==1))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==1)&&(r23==1)&&(r34==1)&&(r45==1))||((r23==1)&&(r34==1)&&(r45==1)&&(r56==1)))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==1)&&(r22==1)&&(r33==1)&&(r44==1))||((r22==1)&&(r33==1)&&(r44==1)&&(r55==1))||((r33==1)&&(r44==1)&&(r55==1)&&(r66==1)))
           {
               ms="Red won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==1)&&(r32==1)&&(r43==1)&&(r54==1))||((r32==1)&&(r43==1)&&(r54==1)&&(r65==1)))
          {
             ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==1)&&(r42==1)&&(r53==1)&&(r64==1))
          {
               ms="Red won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r12==2)&&(r13==2)&&(r14==2))||((r12==2)&&(r13==2)&&(r14==2)&&(r15==2))||((r13==2)&&(r14==2)&&(r15==2)&&(r16==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r21==2)&&(r22==2)&&(r23==2)&&(r24==2))||((r22==2)&&(r23==2)&&(r24==2)&&(r25==2))||((r23==2)&&(r24==2)&&(r25==2)&&(r26==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         else if(((r31==2)&&(r32==2)&&(r33==2)&&(r34==2))||((r32==2)&&(r33==2)&&(r34==2)&&(r35==2))||((r33==2)&&(r34==2)&&(r35==2)&&(r36==2)))
          {
                ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r41==2)&&(r42==2)&&(r43==2)&&(r44==2))||((r42==2)&&(r43==2)&&(r44==2)&&(r45==2))||((r43==2)&&(r44==2)&&(r45==2)&&(r46==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r52==2)&&(r53==2)&&(r54==2))||((r52==2)&&(r53==2)&&(r54==2)&&(r55==2))||((r53==2)&&(r54==2)&&(r55==2)&&(r56==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==2)&&(r62==2)&&(r63==2)&&(r64==2))||((r62==2)&&(r63==2)&&(r64==2)&&(r65==2))||((r63==2)&&(r64==2)&&(r65==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==2)&&(r21==2)&&(r31==2)&&(r41==2))||((r21==2)&&(r31==2)&&(r41==2)&&(r51==2))||((r31==2)&&(r41==2)&&(r51==2)&&(r61==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==2)&&(r22==2)&&(r32==2)&&(r42==2))||((r22==2)&&(r32==2)&&(r42==2)&&(r52==2))||((r32==2)&&(r42==2)&&(r52==2)&&(r62==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==2)&&(r23==2)&&(r33==2)&&(r43==2))||((r23==2)&&(r33==2)&&(r43==2)&&(r53==2))||((r33==2)&&(r43==2)&&(r53==2)&&(r63==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==2)&&(r24==2)&&(r34==2)&&(r44==2))||((r24==2)&&(r34==2)&&(r44==2)&&(r54==2))||((r34==2)&&(r44==2)&&(r54==2)&&(r64==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==2)&&(r25==2)&&(r35==2)&&(r45==2))||((r25==2)&&(r35==2)&&(r45==2)&&(r55==2))||((r35==2)&&(r45==2)&&(r55==2)&&(r65==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==2)&&(r26==2)&&(r36==2)&&(r46==2))||((r26==2)&&(r36==2)&&(r46==2)&&(r56==2))||((r36==2)&&(r46==2)&&(r56==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==2)&&(r32==2)&&(r23==2)&&(r14==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r42==2)&&(r33==2)&&(r24==2))||((r42==2)&&(r33==2)&&(r24==2)&&(r15==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==2)&&(r52==2)&&(r43==2)&&(r34==2))||((r52==2)&&(r43==2)&&(r34==2)&&(r25==2))||((r43==2)&&(r34==2)&&(r25==2)&&(r16==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==2)&&(r53==2)&&(r44==2)&&(r35==2))||((r53==2)&&(r44==2)&&(r35==2)&&(r26==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==2)&&(r54==2)&&(r45==2)&&(r36==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==2)&&(r24==2)&&(r35==2)&&(r46==2))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==2)&&(r23==2)&&(r34==2)&&(r45==2))||((r23==2)&&(r34==2)&&(r45==2)&&(r56==2)))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r22==2)&&(r33==2)&&(r44==2))||((r22==2)&&(r33==2)&&(r44==2)&&(r55==2))||((r33==2)&&(r44==2)&&(r55==2)&&(r66==2)))
           {
               ms="Blue won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==2)&&(r32==2)&&(r43==2)&&(r54==2))||((r32==2)&&(r43==2)&&(r54==2)&&(r65==2)))
          {
             ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==2)&&(r42==2)&&(r53==2)&&(r64==2))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(r==36)
          {
              ms="Match is Draw";
              game12 g12=new game12(ms);
              g12.setVisible(true);
          }
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        r++; 
         if(a6==0)
          {
             if(q%2==0)
             {
                 b66.setBackground(Color.red);
                 q++;
                 a6++;
                 r66=1;
             }
             else
             {
                  b66.setBackground(Color.blue);
                  q++;a6++;
                  r66=2;
             }
          }
         else if(a6==1)
          {
             if(q%2==0)
             {
                 b56.setBackground(Color.red);
                 q++;
                 a6++;
                 r56=1;
             }
             else
             {
                  b56.setBackground(Color.blue);
                  q++;a6++;
                  r56=2;
             }
          }
         else if(a6==2)
          {
             if(q%2==0)
             {
                 b46.setBackground(Color.red);
                 q++;
                 a6++;
                 r46=1;
             }
             else
             {
                  b46.setBackground(Color.blue);
                  q++;a6++;
                  r46=2;
             }
          }
         else if(a6==3)
          {
             if(q%2==0)
             {
                 b36.setBackground(Color.red);
                 q++;
                 a6++;
                 r36=1;
             }
             else
             {
                  b36.setBackground(Color.blue);
                  q++;a6++;
                  r36=2;
             }
          }
         else if(a6==4)
          {
             if(q%2==0)
             {
                 b26.setBackground(Color.red);
                 q++;
                 a6++;
                 r26=1;
             }
             else
             {
                  b26.setBackground(Color.blue);
                  q++;a6++;
                  r26=2;
             }
          }  
         else if(a6==5)
          {
             if(q%2==0)
             {
                 b16.setBackground(Color.red);
                 q++;
                 a6++;
                 r16=1;
             }
             else
             {
                  b16.setBackground(Color.blue);
                  q++;a6++;
                  r16=2;
             }
          } 
           if(((r11==1)&&(r12==1)&&(r13==1)&&(r14==1))||((r12==1)&&(r13==1)&&(r14==1)&&(r15==1))||((r13==1)&&(r14==1)&&(r15==1)&&(r16==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else  if(((r21==1)&&(r22==1)&&(r23==1)&&(r24==1))||((r22==1)&&(r23==1)&&(r24==1)&&(r25==1))||((r23==1)&&(r24==1)&&(r25==1)&&(r26==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r31==1)&&(r32==1)&&(r33==1)&&(r34==1))||((r32==1)&&(r33==1)&&(r34==1)&&(r35==1))||((r33==1)&&(r34==1)&&(r35==1)&&(r36==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
         
          else if(((r41==1)&&(r42==1)&&(r43==1)&&(r44==1))||((r42==1)&&(r43==1)&&(r44==1)&&(r45==1))||((r43==1)&&(r44==1)&&(r45==1)&&(r46==1)))
          {
            ms="Red won the Match";
           
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if(((r51==1)&&(r52==1)&&(r53==1)&&(r54==1))||((r52==1)&&(r53==1)&&(r54==1)&&(r55==1))||((r53==1)&&(r54==1)&&(r55==1)&&(r56==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==1)&&(r62==1)&&(r63==1)&&(r64==1))||((r62==1)&&(r63==1)&&(r64==1)&&(r65==1))||((r63==1)&&(r64==1)&&(r65==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==1)&&(r21==1)&&(r31==1)&&(r41==1))||((r21==1)&&(r31==1)&&(r41==1)&&(r51==1))||((r31==1)&&(r41==1)&&(r51==1)&&(r61==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==1)&&(r22==1)&&(r32==1)&&(r42==1))||((r22==1)&&(r32==1)&&(r42==1)&&(r52==1))||((r32==1)&&(r42==1)&&(r52==1)&&(r62==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==1)&&(r23==1)&&(r33==1)&&(r43==1))||((r23==1)&&(r33==1)&&(r43==1)&&(r53==1))||((r33==1)&&(r43==1)&&(r53==1)&&(r63==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==1)&&(r24==1)&&(r34==1)&&(r44==1))||((r24==1)&&(r34==1)&&(r44==1)&&(r54==1))||((r34==1)&&(r44==1)&&(r54==1)&&(r64==1)))
          {
            ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==1)&&(r25==1)&&(r35==1)&&(r45==1))||((r25==1)&&(r35==1)&&(r45==1)&&(r55==1))||((r35==1)&&(r45==1)&&(r55==1)&&(r65==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==1)&&(r26==1)&&(r36==1)&&(r46==1))||((r26==1)&&(r36==1)&&(r46==1)&&(r56==1))||((r36==1)&&(r46==1)&&(r56==1)&&(r66==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==1)&&(r32==1)&&(r23==1)&&(r14==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==1)&&(r42==1)&&(r33==1)&&(r24==1))||((r42==1)&&(r33==1)&&(r24==1)&&(r15==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==1)&&(r52==1)&&(r43==1)&&(r34==1))||((r52==1)&&(r43==1)&&(r34==1)&&(r25==1))||((r43==1)&&(r34==1)&&(r25==1)&&(r16==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==1)&&(r53==1)&&(r44==1)&&(r35==1))||((r53==1)&&(r44==1)&&(r35==1)&&(r26==1)))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==1)&&(r54==1)&&(r45==1)&&(r36==1))
          {
            ms="Red won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==1)&&(r24==1)&&(r35==1)&&(r46==1))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==1)&&(r23==1)&&(r34==1)&&(r45==1))||((r23==1)&&(r34==1)&&(r45==1)&&(r56==1)))
          {
              ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==1)&&(r22==1)&&(r33==1)&&(r44==1))||((r22==1)&&(r33==1)&&(r44==1)&&(r55==1))||((r33==1)&&(r44==1)&&(r55==1)&&(r66==1)))
           {
               ms="Red won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==1)&&(r32==1)&&(r43==1)&&(r54==1))||((r32==1)&&(r43==1)&&(r54==1)&&(r65==1)))
          {
             ms="Red won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==1)&&(r42==1)&&(r53==1)&&(r64==1))
          {
               ms="Red won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r12==2)&&(r13==2)&&(r14==2))||((r12==2)&&(r13==2)&&(r14==2)&&(r15==2))||((r13==2)&&(r14==2)&&(r15==2)&&(r16==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r21==2)&&(r22==2)&&(r23==2)&&(r24==2))||((r22==2)&&(r23==2)&&(r24==2)&&(r25==2))||((r23==2)&&(r24==2)&&(r25==2)&&(r26==2)))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         else if(((r31==2)&&(r32==2)&&(r33==2)&&(r34==2))||((r32==2)&&(r33==2)&&(r34==2)&&(r35==2))||((r33==2)&&(r34==2)&&(r35==2)&&(r36==2)))
          {
                ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r41==2)&&(r42==2)&&(r43==2)&&(r44==2))||((r42==2)&&(r43==2)&&(r44==2)&&(r45==2))||((r43==2)&&(r44==2)&&(r45==2)&&(r46==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r52==2)&&(r53==2)&&(r54==2))||((r52==2)&&(r53==2)&&(r54==2)&&(r55==2))||((r53==2)&&(r54==2)&&(r55==2)&&(r56==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
        
          else if(((r61==2)&&(r62==2)&&(r63==2)&&(r64==2))||((r62==2)&&(r63==2)&&(r64==2)&&(r65==2))||((r63==2)&&(r64==2)&&(r65==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
            
          }
          
          else if(((r11==2)&&(r21==2)&&(r31==2)&&(r41==2))||((r21==2)&&(r31==2)&&(r41==2)&&(r51==2))||((r31==2)&&(r41==2)&&(r51==2)&&(r61==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r12==2)&&(r22==2)&&(r32==2)&&(r42==2))||((r22==2)&&(r32==2)&&(r42==2)&&(r52==2))||((r32==2)&&(r42==2)&&(r52==2)&&(r62==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
           else if(((r13==2)&&(r23==2)&&(r33==2)&&(r43==2))||((r23==2)&&(r33==2)&&(r43==2)&&(r53==2))||((r33==2)&&(r43==2)&&(r53==2)&&(r63==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
           else if(((r14==2)&&(r24==2)&&(r34==2)&&(r44==2))||((r24==2)&&(r34==2)&&(r44==2)&&(r54==2))||((r34==2)&&(r44==2)&&(r54==2)&&(r64==2)))
          {
            ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r15==2)&&(r25==2)&&(r35==2)&&(r45==2))||((r25==2)&&(r35==2)&&(r45==2)&&(r55==2))||((r35==2)&&(r45==2)&&(r55==2)&&(r65==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          
          else if(((r16==2)&&(r26==2)&&(r36==2)&&(r46==2))||((r26==2)&&(r36==2)&&(r46==2)&&(r56==2))||((r36==2)&&(r46==2)&&(r56==2)&&(r66==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
         
          else if((r41==2)&&(r32==2)&&(r23==2)&&(r14==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r51==2)&&(r42==2)&&(r33==2)&&(r24==2))||((r42==2)&&(r33==2)&&(r24==2)&&(r15==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
        
          else if(((r61==2)&&(r52==2)&&(r43==2)&&(r34==2))||((r52==2)&&(r43==2)&&(r34==2)&&(r25==2))||((r43==2)&&(r34==2)&&(r25==2)&&(r16==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r62==2)&&(r53==2)&&(r44==2)&&(r35==2))||((r53==2)&&(r44==2)&&(r35==2)&&(r26==2)))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r63==2)&&(r54==2)&&(r45==2)&&(r36==2))
          {
            ms="Blue won the Match";
             game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r13==2)&&(r24==2)&&(r35==2)&&(r46==2))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r12==2)&&(r23==2)&&(r34==2)&&(r45==2))||((r23==2)&&(r34==2)&&(r45==2)&&(r56==2)))
          {
              ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(((r11==2)&&(r22==2)&&(r33==2)&&(r44==2))||((r22==2)&&(r33==2)&&(r44==2)&&(r55==2))||((r33==2)&&(r44==2)&&(r55==2)&&(r66==2)))
           {
               ms="Blue won the Match";
           game12 g12=new game12(ms);
            g12.setVisible(true);
           }
          else if(((r21==2)&&(r32==2)&&(r43==2)&&(r54==2))||((r32==2)&&(r43==2)&&(r54==2)&&(r65==2)))
          {
             ms="Blue won the Match";
            game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if((r31==2)&&(r42==2)&&(r53==2)&&(r64==2))
          {
               ms="Blue won the Match";
               game12 g12=new game12(ms);
            g12.setVisible(true);
          }
          else if(r==36)
          {
              ms="Match is Draw";
              game12 g12=new game12(ms);
              g12.setVisible(true);
          }
    }//GEN-LAST:event_c6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton b43;
    private javax.swing.JButton b44;
    private javax.swing.JButton b45;
    private javax.swing.JButton b46;
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JButton b53;
    private javax.swing.JButton b54;
    private javax.swing.JButton b55;
    private javax.swing.JButton b56;
    private javax.swing.JButton b61;
    private javax.swing.JButton b62;
    private javax.swing.JButton b63;
    private javax.swing.JButton b64;
    private javax.swing.JButton b65;
    private javax.swing.JButton b66;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    // End of variables declaration//GEN-END:variables
}
