/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRITHVI MUKESH
 */
public class game2 extends javax.swing.JFrame {

   int q,n=0;
     String a,u,ms;
    public game2(String s,int q,String a,String u) {
        initComponents();
        l2.setText(s);
        this.q=q;
        this.a=a;
        this.u=u;
    }

    private game2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(260, 220, 90, 70);

        b1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(150, 220, 90, 70);

        b5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(610, 220, 90, 70);

        b3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(370, 220, 90, 70);

        b4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(490, 220, 90, 70);

        b7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(260, 320, 90, 70);

        b6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(150, 320, 90, 70);

        b0.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b0.setText("10");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(610, 320, 90, 70);

        b8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(370, 320, 90, 70);

        b9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(490, 320, 90, 70);

        l2.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 36)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(l2);
        l2.setBounds(160, 70, 620, 60);

        jLabel1.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 24)); // NOI18N
        jLabel1.setText("Range of  Total :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 480, 190, 50);

        t2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(390, 480, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numbers-19194-1920x1080.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 940, 610);

        setBounds(0, 0, 959, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
          n=n+1;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			 game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		        game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         n=n+3;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b3ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
         n=n+6;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b6ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        n=n+8;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        n=n+7;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b7ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        n=n+2;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
         n=n+4;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
         n=n+5;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b5ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        n=n+9;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
         n=n+10;
		 t2.setText(Integer.toString(n));
		 q++;
                 if(n==100)
		 {
		    if(q%2==0)
			{
			ms="Hey  "+u+"  you win the match";
			game3 g3=new game3(ms);
                        g3.setVisible(true);}
			else
			{
			  ms="Hey  "+a+"  you win the match";
			  game3 g3=new game3(ms);
                          g3.setVisible(true);}
                 }
                 else if(n>100)
		{
		   ms="Number is out of range";
		    game3 g3=new game3(ms);
                          g3.setVisible(true);
		 }
    }//GEN-LAST:event_b0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel t2;
    // End of variables declaration//GEN-END:variables
}
